---
services:
  postgres:
    container_name: virtual-psychologist-postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  backend:
    container_name: virtual-psychologist-backend
    image: dachereukho17/virtual-psychologist-backend:latest
    ports:
      - "8080:8080"