spring:
  application:
    name: virtual-psychologist-backend

  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/postgres
    username: postgres
    password: postgres

jwt:
  key: bcb37123b6cb7891263cb97126cb978123
  access-token-expiration: 2592000000